package:
  name: dualtree
  version: !!str 0.6


source:
  fn:  boost_1_61_0.tar.bz2
  url: http://sourceforge.net/projects/boost/files/boost/1.61.0/boost_1_61_0.tar.bz2
  md5: 6095876341956f65f9d35939ccea1a9f

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - PyWavelets
    - numpy

test:
  imports:
    - dualtree.tests.test_dt
    - dualtree.tests.test_discrete

about:
  home: http://www.physics.mcgill.ca/siwicklab/
  license_file : LICENSE
  summary: 'Dual-tree complex wavelet transform and algorithms'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml